spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-107-22-101-0.compute-1.amazonaws.com/
    username: izbpoaamrhbkab
    password:
    platform: postgres
    driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update
    properties:
      hibernate.format_sql: true
      show-sql: true

jwt:
  secret-key: ej_media_sns_2023_sharp_stream.secret_key
  token:
    expired-time-ms: 2592000000