spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-107-22-101-0.compute-1.amazonaws.com/doapn3p18mebj
    username: izbpoaamrhbkab
    password: 3636d0e7bdda28a3b566cbe6fd4081d02410bbafd1c073114f498fffabfc48e7
    platform: postgres
    driver-class-name: org.postgresql.Driver

  redis:
    url: redis://:p1f2bc45af9a651be1e8c98bb3ae3461ee0b5b435cfd2717a5a8e11ef7e77c62f@ec2-174-129-182-178.compute-1.amazonaws.com:15989

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: ej_media_sns_2023_sharp_stream.secret_key
  token:
    expired-time-ms: 2592000000

#logging:
#  level:
#    root: DEBUG